panel:
    path:     /
    defaults: { _controller: PanelBundle:Auth:login }

panel.login:
    path:     /login
    defaults: { _controller: PanelBundle:Auth:login }

panel.logout:
    path:     /logout
    defaults: { _controller: PanelBundle:Auth:logout }

panel.login.control:
    path:     /login/control
    defaults: { _controller: PanelBundle:Auth:control}

panel.dashboard:
    path:   /dashboard
    defaults: {_controller: PanelBundle:Auth:dashboard}

#/mod_user/user_list
panel.mod_user:
    path:     /mod_user/user_list
    defaults: { _controller: PanelBundle:ModUser:list}

#/mod_user_group/group_list
panel.mod_user_group:
    path:   /mod_user_group/group_list
    defaults: { _controller: PanelBundle:ModUserGroup:list}

#/mod_meeting/list
panel.mod_meeting:
    path:   /mod_meeting/list
    defaults: { _controller: PanelBundle:ModMeeting:list}
panel.mod_meeting_meeting:
    path:   /mod_meeting/meeting
    defaults: { _controller: PanelBundle:ModMeeting:meeting}