services:
#    panel.example:
#        class: PanelBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    panel.user:
        class: PanelBundle\Service\UserServices
        arguments: [ "@doctrine.orm.entity_manager" ]
        public: true

    panel.lang:
            class: PanelBundle\Service\MultiLangServices
            arguments: ['@service_container']
            public: true