panel:
    resource: "@PanelBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/panel/

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/api/
#    schemes: [https]
app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
