# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.locale:
        class: 'ApiBundle\Service\LocaleService'
        arguments: ["@kernel"]
        tags:
            - {name: kernel.event_listener , event: kernel.controller, priotry: 5000}


imports:
    - { resource: "@PanelBundle/Resources/config/services.yml" }
    - { resource: "@ApiBundle/Resources/config/services.yml" }
