<?php

namespace ApiBundle\Repository;

/**
 * ModUserAuthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModUserAuthRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAuth($param){
       return $this -> getEntityManager()
           ->getRepository('ApiBundle:ModUserAuth')
           ->findOneBy(
               [
                'groupId' => $param['group'],
                'rollId'  => $param['roll'],
                'modId'   => $param['mod'],
               ]
           );
    }
    public function getUserAuth($groupId){
        $dql = 'SELECT mua FROM ApiBundle:ModUserAuth mua WHERE mua.groupId = :group_id';
        return  $this -> getEntityManager()
                      -> createQuery($dql)
                      -> setParameter('group_id',$groupId)
                      -> getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }
}
